/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tensionalsimulator;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.io.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.Timer;

/**
 *
 * @author waheed
 */
public class tensionMachine extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form tensionMachine
     */
    Timer ti = new Timer(70,this);
    int x=500, velx = 1;
    public tensionMachine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tension Simulation Window™");
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    String[] retJa(){
        String[] k = new String[6];
        try{
        FileReader fr = new FileReader("data.txt");        
        char [] a = new char[50];
        fr.read(a); // reads the content to the array
        int counter = 0;
        String charPart = "";
        for(char c : a)           
            if(c == '\n'){
                k[counter]= charPart;
                charPart = "";
                counter++;
            }
            else{
                //System.out.print(c);
                charPart = charPart+""+c;
            }
        fr.close();
        }
        catch(Exception e){
            k[0] = "";
            k[1] = "";
            k[2] = "";
            k[3] = "";
            k[4] = "";
        }
        return k;
    }
    public void paint(Graphics g){
        //Image im = Toolkit.getDefaultToolkit().getImage("j.fw.png");
        g.setColor(Color.DARK_GRAY);
        g.fillRect(50, 250, 100, 300);
        g.fillRect(50, 450, 800, 100);
        g.setColor(Color.WHITE);
        g.drawLine(150, 480, 680+150, 480);
        g.drawLine(150, 480, 150, 500);
        g.drawLine(680+150, 480, 680+150, 500);
        int zi = 0;
        while(zi < 680){
            int xRef = 150;
            int yRef = 500;
            g.drawLine(xRef+zi, yRef, xRef+zi+5, yRef+10);
            g.drawLine(xRef+zi+5, yRef+10, xRef+zi+10, yRef);
            zi = zi +10;
        }
        g.setColor(Color.DARK_GRAY);
        g.fillRect(x, 250, 150, 300); //movable jaw
        g.setColor(Color.WHITE);
        g.drawRect(x, 249, 150, 302); //movable jaw
        g.fillOval(x+50, 480, 50, 50); //movable knob
        g.setColor(Color.DARK_GRAY);
        g.drawOval(x+52, 482, 46, 46); //movable knob
        g.setColor(Color.darkGray);
        g.fillRect(5, 580, 890, 20);
        g.fillOval(100, 560, 50, 50);
        g.fillOval(800, 560, 50, 50);
        g.fillRect(110, 550, 30, 50);
        g.fillRect(810, 550, 30, 50);
        g.setColor(Color.WHITE);
        g.drawLine(0, 579, 900, 579);
        g.setColor(Color.blue); //Specimen
        g.fillRect(175, 250, 300, 50); //Main body
        g.setColor(Color.DARK_GRAY);
        g.fillRect(150, 250, 25, 50); //hinge
        g.fillRect(x-25, 250, 27, 50); //hinge
        g.setColor(Color.WHITE);
        g.fillOval(140, 265, 20, 20);
        g.setColor(Color.blue); //hinge Spike
        g.fillOval(142, 267, 16, 16);
        g.setColor(Color.DARK_GRAY);
        g.fillOval(145, 270, 10, 10);
        g.setColor(Color.WHITE);
        g.fillOval(x-10, 265, 20, 20);
        g.setColor(Color.blue); //Hinge Spike 2
        g.fillOval(x-8, 267, 16, 16);
        g.setColor(Color.DARK_GRAY);
        g.fillOval(x-5, 270, 10, 10);
        g.setColor(Color.white);
        /*g.fillArc(160,235,30,30,0,-90);
        g.fillArc(160,285,30,30,0,90);
        g.fillArc(460,235,30,30,-90,-90);
        g.fillArc(460,285,30,30,-180,-90);*/
        if(x < 650){
            ti.start();
        }
        else{
            ti.stop();
        }
        //g.drawImage(im, 550, 480, 50, 50, rootPane);
    }
    public void actionPerformed(ActionEvent e){
        x = x + 1;
        repaint();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tensionMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tensionMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tensionMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tensionMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tensionMachine().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
